// src/views/components/ExperienceModal.vue
<template>
  <div>
    <v-btn
      variant="text"
      :ripple="false"
      class="pa-0"
      style="border: none; min-width: auto;"
      @click="openModal"
    >
      <v-avatar :aria-label="`company: ${company}`">
        <v-img
          v-if="companyLogo"
          :src="companyLogo"
          :alt="company"
        />
        <span v-else>{{ companyInitials }}</span>
      </v-avatar>
    </v-btn>

    <v-dialog
      v-model="isModalOpen"
      max-width="600"
      :aria-labelledby="position"
    >
      <v-card>
        <v-card-title class="d-flex justify-space-between align-center pa-4">
          <div>
            <h2 class="text-h5 text-primary">
              {{ position }} @ {{ company }}
            </h2>
          </div>
          <v-btn
            icon
            variant="text"
            @click="closeModal"
            aria-label="close"
          >
            <v-avatar size="32">
              <v-img
                v-if="companyLogo"
                :src="companyLogo"
                :alt="company"
              />
              <span v-else>{{ companyInitials }}</span>
            </v-avatar>
          </v-btn>
        </v-card-title>

        <v-divider />

        <v-card-text class="pa-4" style="max-height: 400px; overflow-y: auto;">
          <div
            v-for="(task, index) in tasks"
            :key="index"
            class="mb-3"
          >
            <p class="text-body-1">
              {{ task }}
            </p>
          </div>
        </v-card-text>

        <v-divider />

        <v-card-actions class="pa-4">
          <v-spacer />
          <v-btn
            color="primary"
            @click="closeModal"
            autofocus
          >
            Close
          </v-btn>
        </v-card-actions>
      </v-card>
    </v-dialog>
  </div>
</template>

<script setup lang="ts">
import type { Experience } from '@/models/entities/experience';
import { useExperienceModal } from '@/viewmodels/components/useExperienceModal';

const props = defineProps<Experience>()

const {
    isModalOpen,
    openModal,
    closeModal,
    companyInitials
  } = useExperienceModal(props)
</script>

// src/aboutMe/components/experience-modal.tsx
import Avatar from '@mui/material/Avatar';
import Typography from '@mui/material/Typography';
import React, { FC } from 'react';
import Experience from '../entities/experience';
import TimelineDot from '@mui/lab/TimelineDot';
import Button from '@mui/material/Button';
import Dialog from '@mui/material/Dialog';
import DialogTitle from '@mui/material/DialogTitle';
import IconButton from '@mui/material/IconButton';
import DialogContent from '@mui/material/DialogContent';
import DialogActions from '@mui/material/DialogActions';

const ExperienceDialog: FC<Experience> = (xp: Experience) => {
  const [open, setOpen] = React.useState(false);

  const handleClickOpen = () => {
    setOpen(true);
  };
  const handleClose = () => {
    setOpen(false);
  };

  const { company, companyLogo, position, tasks } =
    xp;
  return (
    <>
    <Button variant="outlined" onClick={handleClickOpen} sx={{border: "none", p:0}}>
      <TimelineDot variant="outlined" sx={{ p: 0 }}>
          <Avatar aria-label="company" src={companyLogo} />
        </TimelineDot>
    </Button>
    <Dialog onClose={handleClose}
      aria-labelledby="{position}"
      open={open}>
      <DialogTitle sx={{ m: 0, p: 2 }}>
        <Typography variant="h5" color="text.primary">
          {position} @ {company}
        </Typography>
      </DialogTitle>
      <IconButton
        aria-label="close"
        onClick={handleClose}
        sx={{
          position: 'absolute',
          right: 8,
          top: 8,
        }}
      >
        <Avatar aria-label="company" src={companyLogo} />
      </IconButton>
      <DialogContent dividers>
        {tasks.map((task, index) => (
          <Typography gutterBottom key={index}>
            {task}
          </Typography>
        ))}
      </DialogContent>
      <DialogActions>
        <Button autoFocus onClick={handleClose}>
          Close
        </Button>
      </DialogActions>
    </Dialog>
    </>
  );
};

export default ExperienceDialog;
