// src/aboutMe/components/experience-timeline.tsx
import Timeline from '@mui/lab/Timeline';
import TimelineItem from '@mui/lab/TimelineItem';
import TimelineSeparator from '@mui/lab/TimelineSeparator';
import TimelineConnector from '@mui/lab/TimelineConnector';
import TimelineContent from '@mui/lab/TimelineContent';
import Card from '@mui/material/Card';
import Box from '@mui/material/Box';
import Chip from '@mui/material/Chip';
import Stack from '@mui/material/Stack';
import Divider from '@mui/material/Divider';
import Typography from '@mui/material/Typography';
import Experience from '../entities/experience';
import { FC } from 'react';
import { useTranslation } from 'react-i18next';
import TimelineOppositeContent from '@mui/lab/TimelineOppositeContent/TimelineOppositeContent';
import ExperienceDialog from './experience-modal';

const ExperiencesTimeline: FC = () => {
  const { t } = useTranslation('professional-experiences');
  return (
      <Timeline position="alternate">
        {t<string, Experience[]>('professional-experiences', {
          returnObjects: true,
        }).map(( xp : Experience, index: number) => (
          <TimelineItem key={index}>
            <TimelineOppositeContent
              sx={{ m: '17px 0' }}
              align="right"
              variant="body2"
              color="text.secondary"
            >
                {xp.timeRanges}
            </TimelineOppositeContent>
            <TimelineSeparator>
              <ExperienceDialog {...xp} />
              <TimelineConnector />
            </TimelineSeparator>
            <TimelineContent sx={{ width: '20%', minWidth: '270px' }}>
              <Card variant="outlined">
                <Box sx={{ p: 2 }}>
                  <Stack
                    direction="row"
                    sx={{ justifyContent: 'space-between', alignItems: 'center' }}
                  >
                    <Typography gutterBottom variant="h5" component="div">
                      {xp.position}
                    </Typography>
                    <Typography gutterBottom variant="h6" component="div" display={{xs: 'none', lg: 'block'}}>
                      {xp.company}
                    </Typography>
                  </Stack>
                  <Typography variant="body2" sx={{ color: 'text.secondary' }}>
                    {xp.context}
                  </Typography>
                </Box>
                <Divider />
                <Box sx={{ p: 2, overflowX: 'scroll'}}>
                  <Stack direction="row" spacing={1} >
                    {xp.tags.map((tag, index) => (
                      <Chip label={tag} size="small" key={index} />
                    ))}
                  </Stack>
                </Box>
              </Card>
            </TimelineContent>
          </TimelineItem>
        ))}
        </Timeline>
  );
};

export default ExperiencesTimeline;

// src/views/components/ExperienceTimeline.vue
<template>
  <v-timeline
    side="end"
    align="start"
  >
    <v-timeline-item
      v-for="(experience, index) in experiences"
      :key="index"
      fill-dot
    >
      <template #icon>
        <ExperienceModal v-bind="experience" />
      </template>

      <template #opposite>
        <div class="text-body-2 text-medium-emphasis ma-4">
          {{ experience.timeRanges }}
        </div>
      </template>

      <v-card
        variant="outlined"
        style="min-width: 270px; width: 20%;"
      >
        <v-card-text>
          <div class="d-flex justify-space-between align-center">
            <h5 class="text-h5">
              {{ experience.position }}
            </h5>
            <h6 class="text-h6 d-none d-lg-block">
              {{ experience.company }}
            </h6>
          </div>

          <p class="text-body-2 text-medium-emphasis mt-2">
            {{ experience.context }}
          </p>
        </v-card-text>

        <v-divider />

        <v-card-text
          class="pa-2"
          style="overflow-x: auto;"
        >
          <div class="d-flex ga-1 flex-nowrap">
            <v-chip
              v-for="(tag, tagIndex) in experience.tags"
              :key="tagIndex"
              size="small"
            >
              {{ tag }}
            </v-chip>
          </div>
        </v-card-text>
      </v-card>
    </v-timeline-item>
  </v-timeline>
</template>

<script setup lang="ts">
import { useExperienceTimeline } from '@/viewmodels/components/useExperienceTimeline';
import ExperienceModal from './ExperienceModal.vue';

const { experiences } = useExperienceTimeline()
</script>
